name: TTMBPhoto
favicon: null
layout_spectrum: 0.24329699319787323
typography_spectrum: 0.48554984806105494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25699973991140723
  lightness: 0.6366898566484451
  saturation: 0.5595335594844073
  rhythmicContrast: 0.40255492785945535
purpose: []
